### ISSUE TITLE
test new prow bot

### ISSUE THREAD

**Issue by Tomcli** [kserve/prow-tests#9]

**Comment by ghost** [comment]
@Tomcli: Closing this issue.

<details>

In response to [this](https://github.com/kserve/prow-tests/issues/9#issuecomment-1830785746):

>/close


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>
